settings:
  title: 'pranchi.xyz Statuspage'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Degraded Performance'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'System Down'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: pranchi-xyz # unique identifier
    name: Website
    description: 'Main Website' # default=empty
    url: 'https://www.pranchi.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: Cloudflare
    description: 'DNS and CDN provider of pranchi.xyz'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: autodiscover-pranchi-xyz
    name: Mail Service (Outlook 365)
    url: 'https://autodiscover.pranchi.xyz/'
    method: GET
    expectStatus: 200
    followRedirect: true
